### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by phgmacedo** [gjsjohnmurray/webterminal-vscode#5]
I can't answer your question because I was blocked from msft. https://github.com/microsoft/vscode-jupyter/issues/11027#issuecomment-1203445042

**Comment by gjsjohnmurray** [comment]
So can you answer it here? Or shall I close this issue as off topic to the repository you opened it on?

**Comment by phgmacedo** [comment]
Yeah, it's probably off topic. I'll try using the keyboard tomorrow.

**Comment by phgmacedo** [comment]
Pressing ctrl+c does not work either, but in this particular case, it shouldn’t, because I’m clicking a single cell, so the expectation would be that only the single cell value is copied.
