### ISSUE TITLE
WebTerminal access on non-Primary Mirrors

### ISSUE THREAD

**Issue by theflyingape** [gjsjohnmurray/webterminal-vscode#7]
The WebTerminal installer places both the package class & its cookie sessions in a namespace. You may want that code mirrored, but not its session cookies.

Connecting to /terminal/ on a backup mirror fails with:
```
Terminal load complete.
Getting auth key...Unknown server response: %s
```
Is there a better place than a local global, such as a FileStream, to manage WebTerminal session cookies for mirrorsets?

**Comment by gjsjohnmurray** [comment]
I think this issue belongs in https://github.com/intersystems-community/webterminal/issues

As a workaround I guess you could %ALL-map the ^WebTerminal global to IRISTEMP instead of to the database of the namespace into which you installed the WebTerminal package.
